/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_erickcarrasco;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author erick
 */
public class Principal_frame extends javax.swing.JFrame {

    /**
     * Creates new form Principal_frame
     */
        
    administrarClientes ac = new administrarClientes("./clientes.txt");
    administrarMantenimiento am = new administrarMantenimiento("./mantenimiento.txt");
    administradorATM atm = new administradorATM("./atms.txt");
    public Principal_frame() {
        initComponents();
        admins.add(new Administrador("admin", "admin", "12345"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_register = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        crearuser = new javax.swing.JButton();
        crearatm = new javax.swing.JButton();
        jb_personal_atm = new javax.swing.JButton();
        jd_administrator = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_admin = new javax.swing.JTextField();
        pf_admin = new javax.swing.JPasswordField();
        jb_admin_ingresar = new javax.swing.JButton();
        jd_user_create = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        tf_id_user_create = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_nombre_create_iuser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_apellido_user = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_segundonombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_segundoapellido_user = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pf_create_user = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_transacciones = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_birthdate = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tf_affilation = new javax.swing.JTextField();
        cb_type_user = new javax.swing.JComboBox();
        jb_crearuser_xp = new javax.swing.JButton();
        jd_newatm = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tf_atm_ubicacion = new javax.swing.JTextField();
        cb_mantenimiento = new javax.swing.JComboBox();
        tf_id_atm = new javax.swing.JTextField();
        tf_productiondate_atm = new javax.swing.JTextField();
        jb_crear_atm = new javax.swing.JButton();
        jd_personnel = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_personal_mantenimiento = new javax.swing.JTree();
        Popup_addatm = new javax.swing.JPopupMenu();
        jmi_addatm = new javax.swing.JMenuItem();
        jd_agregar_atm = new javax.swing.JDialog();
        cb_atms_disponibles = new javax.swing.JComboBox();
        jb_add_atm_to_user = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jb_ingresar = new javax.swing.JButton();
        jb_administrar = new javax.swing.JButton();
        cb_atms = new javax.swing.JComboBox();

        jLabel5.setText("Creation Admin");

        crearuser.setText("Usuario");
        crearuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearuserMouseClicked(evt);
            }
        });

        crearatm.setText("ATM");
        crearatm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearatmMouseClicked(evt);
            }
        });

        jb_personal_atm.setText("Agregar atm a personal");
        jb_personal_atm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_personal_atmMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_registerLayout = new javax.swing.GroupLayout(jd_register.getContentPane());
        jd_register.getContentPane().setLayout(jd_registerLayout);
        jd_registerLayout.setHorizontalGroup(
            jd_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registerLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel5)
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(jd_registerLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jd_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_registerLayout.createSequentialGroup()
                        .addComponent(jb_personal_atm)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jd_registerLayout.createSequentialGroup()
                        .addComponent(crearuser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(crearatm)
                        .addGap(59, 59, 59))))
        );
        jd_registerLayout.setVerticalGroup(
            jd_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(56, 56, 56)
                .addGroup(jd_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearuser)
                    .addComponent(crearatm))
                .addGap(38, 38, 38)
                .addComponent(jb_personal_atm)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel2.setText("Credenciales");

        jLabel3.setText("User: ");

        jLabel4.setText("Password: ");

        jb_admin_ingresar.setText("Ingresar");
        jb_admin_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_admin_ingresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_administratorLayout = new javax.swing.GroupLayout(jd_administrator.getContentPane());
        jd_administrator.getContentPane().setLayout(jd_administratorLayout);
        jd_administratorLayout.setHorizontalGroup(
            jd_administratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_administratorLayout.createSequentialGroup()
                .addGroup(jd_administratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_administratorLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel2))
                    .addGroup(jd_administratorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_administratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(48, 48, 48)
                        .addGroup(jd_administratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_admin)
                            .addComponent(pf_admin, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_administratorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jb_admin_ingresar)
                .addGap(126, 126, 126))
        );
        jd_administratorLayout.setVerticalGroup(
            jd_administratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_administratorLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jd_administratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jd_administratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pf_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_admin_ingresar)
                .addGap(5, 5, 5))
        );

        jLabel6.setText("ID: ");

        jLabel7.setText("Nombre:");

        jLabel8.setText("Apellido:");

        jLabel9.setText("Segundo Nombre:");

        jLabel10.setText("Segundo Nombre:");

        jLabel11.setText("Password:");

        jLabel12.setText("Type:");

        jLabel13.setText("Transacciones: ");

        jLabel14.setText("Birth Date");

        jLabel15.setText("Affilation Year:");

        cb_type_user.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mantenimiento", "Cliente" }));

        jb_crearuser_xp.setText("Crear");
        jb_crearuser_xp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearuser_xpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_user_createLayout = new javax.swing.GroupLayout(jd_user_create.getContentPane());
        jd_user_create.getContentPane().setLayout(jd_user_createLayout);
        jd_user_createLayout.setHorizontalGroup(
            jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_user_createLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_id_user_create, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_user_createLayout.createSequentialGroup()
                        .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_user_createLayout.createSequentialGroup()
                                                        .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel6)
                                                            .addComponent(jLabel7)
                                                            .addComponent(jLabel8))
                                                        .addGap(73, 73, 73))
                                                    .addGroup(jd_user_createLayout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addGap(28, 28, 28)))
                                                .addGroup(jd_user_createLayout.createSequentialGroup()
                                                    .addComponent(jLabel10)
                                                    .addGap(28, 28, 28)))
                                            .addGroup(jd_user_createLayout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(61, 61, 61)))
                                        .addGroup(jd_user_createLayout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(36, 36, 36)))
                                    .addGroup(jd_user_createLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(67, 67, 67)))
                                .addGroup(jd_user_createLayout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(41, 41, 41)))
                            .addGroup(jd_user_createLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(87, 87, 87)))
                        .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_crearuser_xp)
                            .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tf_nombre_create_iuser, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_apellido_user, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_segundonombre, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_segundoapellido_user, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pf_create_user, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_transacciones, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_affilation, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cb_type_user, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jd_user_createLayout.setVerticalGroup(
            jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_user_createLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_id_user_create, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_nombre_create_iuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_segundonombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_apellido_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_segundoapellido_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pf_create_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_transacciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_affilation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(cb_type_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jb_crearuser_xp)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel16.setText("Ubicacion");

        jLabel17.setText("ID");

        jLabel18.setText("Production Date");

        jLabel19.setText("Mantenimiento");

        cb_mantenimiento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semanal", "Mensualmente" }));

        jb_crear_atm.setText("Crear ATM");
        jb_crear_atm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crear_atmMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_newatmLayout = new javax.swing.GroupLayout(jd_newatm.getContentPane());
        jd_newatm.getContentPane().setLayout(jd_newatmLayout);
        jd_newatmLayout.setHorizontalGroup(
            jd_newatmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_newatmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_newatmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(35, 35, 35)
                .addGroup(jd_newatmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_atm_ubicacion)
                    .addComponent(cb_mantenimiento, 0, 131, Short.MAX_VALUE)
                    .addComponent(tf_id_atm)
                    .addComponent(tf_productiondate_atm)
                    .addGroup(jd_newatmLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jb_crear_atm)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jd_newatmLayout.setVerticalGroup(
            jd_newatmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_newatmLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jd_newatmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_atm_ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_newatmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_id_atm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_newatmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_productiondate_atm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_newatmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cb_mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jb_crear_atm)
                .addGap(53, 53, 53))
        );

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Personnel");
        jt_personal_mantenimiento.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_personal_mantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_personal_mantenimientoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_personal_mantenimiento);

        javax.swing.GroupLayout jd_personnelLayout = new javax.swing.GroupLayout(jd_personnel.getContentPane());
        jd_personnel.getContentPane().setLayout(jd_personnelLayout);
        jd_personnelLayout.setHorizontalGroup(
            jd_personnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_personnelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jd_personnelLayout.setVerticalGroup(
            jd_personnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_personnelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jmi_addatm.setText("Agregar atm");
        jmi_addatm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_addatmActionPerformed(evt);
            }
        });
        Popup_addatm.add(jmi_addatm);

        jb_add_atm_to_user.setText("Agregar");
        jb_add_atm_to_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_add_atm_to_userMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_agregar_atmLayout = new javax.swing.GroupLayout(jd_agregar_atm.getContentPane());
        jd_agregar_atm.getContentPane().setLayout(jd_agregar_atmLayout);
        jd_agregar_atmLayout.setHorizontalGroup(
            jd_agregar_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregar_atmLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jd_agregar_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_add_atm_to_user)
                    .addComponent(cb_atms_disponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jd_agregar_atmLayout.setVerticalGroup(
            jd_agregar_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregar_atmLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb_atms_disponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jb_add_atm_to_user)
                .addGap(40, 40, 40))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Eurostile Extended", 0, 18)); // NOI18N
        jLabel1.setText("ATM");

        jb_ingresar.setText("Ingresar ");

        jb_administrar.setText("Crear");
        jb_administrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_administrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_atms, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jb_administrar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jb_ingresar)
                .addGap(76, 76, 76)
                .addComponent(cb_atms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jb_administrar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_administrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_administrarMouseClicked
        // TODO add your handling code here:
        tf_admin.setText("");
        pf_admin.setText("");
        jd_administrator.setModal(true);
        jd_administrator.pack();
        jd_administrator.setLocationRelativeTo(this);
        jd_administrator.setVisible(true);
    }//GEN-LAST:event_jb_administrarMouseClicked

    private void jb_admin_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_admin_ingresarMouseClicked
        // TODO add your handling code here:
        String pass_verify=pf_admin.getText();
        String user= tf_admin.getText();
        String pass;
        String user_auth="";
        int c=0;
        int count=0;
        for (Object P : admins) {
            String userad = admins.get(c).getUser();
            if (user.equals(userad)) {
                user_auth= userad;
                count = c;
            }
            c++;
        }
        pass = admins.get(count).getPassword();
        if (pass_verify.equals(pass) && user.equals(user_auth)) {
            JOptionPane.showMessageDialog(jd_administrator, "Ingreso exitosamente "+ admins.get(count).getNombre());
            
            tf_admin.setText("");
            pf_admin.setText("");
            
            jd_register.setModal(true);
            jd_register.pack();
            jd_register.setLocationRelativeTo(this);
            jd_register.setVisible(true);
            jd_administrator.dispose();
        }
    }//GEN-LAST:event_jb_admin_ingresarMouseClicked

    private void crearuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearuserMouseClicked
        // TODO add your handling code here:
        jd_user_create.setModal(true);
        jd_user_create.pack();
        jd_user_create.setLocationRelativeTo(jd_register);
        jd_user_create.setVisible(true);
    }//GEN-LAST:event_crearuserMouseClicked

    private void jb_crearuser_xpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearuser_xpMouseClicked
        // TODO add your handling code here:
        String type = cb_type_user.getSelectedItem().toString();
        if (type.equals("Cliente")) {
            ac.cargarArchivo();
            String nombre, nombre2, apellido, apellido2, clave, birth, affilacion;
            String id;
            clave = pf_create_user.getText();
            nombre = tf_nombre_create_iuser.getText();
            nombre2 = tf_segundonombre.getText();
            apellido = tf_apellido_user.getText();
            apellido2 = tf_segundoapellido_user.getText();
            birth = tf_birthdate.getText();
            affilacion = tf_affilation.getText();
            id = tf_id_user_create.getText();

            int c = 0;
            boolean validador = true;
            for (Cliente p : ac.getListaClientes()) {
                String user = ac.getListaClientes().get(c).getId();
                if (user.equals(id)) {
                    JOptionPane.showMessageDialog(jd_user_create, "ID ya ocupada");
                    
                    validador = false;
                }
                c++;
            }
        
            if (validador) {
                ac.setCliente(new Cliente(id, nombre, nombre2, apellido, apellido2, clave, birth, affilacion));
                try {
                    ac.escribirArchivo();
                } catch (IOException ex) {
                    //Logger.getLogger(Login_menu.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(jd_user_create, "Se ingreso un nuevo usuario");
                jd_user_create.dispose();
                tf_id_user_create.setText("");
                tf_affilation.setText("");
                tf_birthdate.setText("");
                tf_apellido_user.setText("");
                tf_segundoapellido_user.setText("");
                tf_transacciones.setText("");
                tf_nombre_create_iuser.setText("");
                pf_create_user.setText("");
                //pf_password_nueva.setText("");
            }
            
            
        }
        if (type.equals("Mantenimiento")) {
            am.cargarArchivo();
            String nombre, nombre2, apellido, apellido2, clave, birth, affilacion;
            String id;
            clave = pf_create_user.getText();
            nombre = tf_nombre_create_iuser.getText();
            nombre2 = tf_segundonombre.getText();
            apellido = tf_apellido_user.getText();
            apellido2 = tf_segundoapellido_user.getText();
            birth = tf_birthdate.getText();
            affilacion = tf_affilation.getText();
            id = tf_id_user_create.getText();
            
            int c = 0;
            boolean validador = true;
            for (Mantenimiento m : am.getListaMantenimiento()) {
                String user = am.getListaMantenimiento().get(c).getId();
                if (user.equals(id)) {
                    JOptionPane.showMessageDialog(jd_user_create, "ID ya ocupada");
                    
                    validador = false;
                }
                c++;
            }
            
            if (validador) {
                am.setMantenimiento(new Mantenimiento(id, nombre, nombre2, apellido, apellido2, clave, birth, affilacion));
                try {
                    am.escribirArchivo();
                } catch (IOException ex) {
                    //Logger.getLogger(Login_menu.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(jd_user_create, "Se ingreso un nuevo usuario");
                jd_user_create.dispose();
                tf_id_user_create.setText("");
                tf_affilation.setText("");
                tf_birthdate.setText("");
                tf_apellido_user.setText("");
                tf_segundoapellido_user.setText("");
                tf_transacciones.setText("");
                tf_nombre_create_iuser.setText("");
                pf_create_user.setText("");
                //pf_password_nueva.setText("");
            }
            
        }
        
    }//GEN-LAST:event_jb_crearuser_xpMouseClicked

    private void crearatmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearatmMouseClicked
        // TODO add your handling code here:
        jd_newatm.setModal(true);
        jd_newatm.pack();
        jd_newatm.setLocationRelativeTo(jd_register);
        jd_newatm.setVisible(true);
    }//GEN-LAST:event_crearatmMouseClicked

    private void jb_crear_atmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crear_atmMouseClicked
        // TODO add your handling code here:
        atm.cargarArchivo();
        String ubicacion, id, date, maintenance;
        id = tf_id_atm.getText();
        ubicacion = tf_atm_ubicacion.getText();
        date = tf_productiondate_atm.getText();
        maintenance = cb_mantenimiento.getSelectedItem().toString();
        int c = 0;
        boolean validador = true;
        for (atm m : atm.getAtms()) {
            String user = atm.getAtms().get(c).getId();
            if (user.equals(id)) {
                JOptionPane.showMessageDialog(jd_user_create, "ID ya ocupada");

                validador = false;
            }
            c++;
        }
        
        if (validador) {
            atm.setATM(new atm(ubicacion, id, date, maintenance));
            try {
                    atm.escribirArchivo();
                } catch (IOException ex) {
                    //Logger.getLogger(Login_menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            JOptionPane.showMessageDialog(jd_newatm, "Se ingreso un nuevo atm");
            jd_newatm.dispose();
            tf_atm_ubicacion.setText("");
            tf_productiondate_atm.setText("");
            tf_id_atm.setText("");
            
        }

    }//GEN-LAST:event_jb_crear_atmMouseClicked

    private void jb_personal_atmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_personal_atmMouseClicked
        // TODO add your handling code here:
        DefaultTreeModel modeloARBOL
                = (DefaultTreeModel) jt_personal_mantenimiento.getModel();
        jt_personal_mantenimiento.removeAll();
        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) modeloARBOL.getRoot();
        am.cargarArchivo();

        String nombre, nombre2, apellido, apellido2, clave, birth, affilacion, id;
        int counter = 0;
        for (Mantenimiento m : am.getListaMantenimiento()) {
            nombre = am.getListaMantenimiento().get(counter).getNombre();
            nombre2 = am.getListaMantenimiento().get(counter).getSegundonombre();
            apellido = am.getListaMantenimiento().get(counter).getApellido();
            apellido2 = am.getListaMantenimiento().get(counter).getSegapellido();
            clave = am.getListaMantenimiento().get(counter).getPassword();
            birth = am.getListaMantenimiento().get(counter).getBirthdate();
            affilacion = am.getListaMantenimiento().get(counter).getAffilation();
            id = am.getListaMantenimiento().get(counter).getId();

            DefaultMutableTreeNode p
                    = new DefaultMutableTreeNode(
                            new Mantenimiento(id, nombre, nombre2, apellido, apellido2,
                                    clave, birth, affilacion)
                    );

            raiz.add(p);

            modeloARBOL.reload();
            counter++;
        }
        jd_personnel.setModal(true);
        jd_personnel.pack();
        jd_personnel.setLocationRelativeTo(jd_register);
        jd_personnel.setVisible(true);
          
        
    }//GEN-LAST:event_jb_personal_atmMouseClicked

    private void jt_personal_mantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_personal_mantenimientoMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            int row = jt_personal_mantenimiento.getClosestRowForLocation(evt.getX(),evt.getY());
            jt_personal_mantenimiento.setSelectionRow(row);
            Object v1
                    = jt_personal_mantenimiento.getSelectionPath().
                            getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof Mantenimiento) {
                mant_seleccionado
                        = (Mantenimiento)  nodo_seleccionado.
                                getUserObject();
                Popup_addatm.show(evt.getComponent(), 
                        evt.getX(), evt.getY());
            }
            
        }
    }//GEN-LAST:event_jt_personal_mantenimientoMouseClicked

    private void jmi_addatmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_addatmActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel modeloc = (DefaultComboBoxModel) cb_atms_disponibles.getModel();
        int counter_s = 0;
        for (atm a : atm.getAtms()) {
            modeloc.addElement(atm.getAtms().get(counter_s).getId());
            counter_s++;
        }
        jd_agregar_atm.setModal(true);
        jd_agregar_atm.pack();
        jd_agregar_atm.setLocationRelativeTo(jd_register);
        jd_register.setVisible(true);

    }//GEN-LAST:event_jmi_addatmActionPerformed

    private void jb_add_atm_to_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_add_atm_to_userMouseClicked
        // TODO add your handling code here:
        mant_seleccionado.setAtm(cb_atms_disponibles.getSelectedItem().toString());
        JOptionPane.showMessageDialog(jd_agregar_atm, "Se ha agregado");
        jd_agregar_atm.dispose();
    }//GEN-LAST:event_jb_add_atm_to_userMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu Popup_addatm;
    private javax.swing.JComboBox cb_atms;
    private javax.swing.JComboBox cb_atms_disponibles;
    private javax.swing.JComboBox cb_mantenimiento;
    private javax.swing.JComboBox cb_type_user;
    private javax.swing.JButton crearatm;
    private javax.swing.JButton crearuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_add_atm_to_user;
    private javax.swing.JButton jb_admin_ingresar;
    private javax.swing.JButton jb_administrar;
    private javax.swing.JButton jb_crear_atm;
    private javax.swing.JButton jb_crearuser_xp;
    private javax.swing.JButton jb_ingresar;
    private javax.swing.JButton jb_personal_atm;
    private javax.swing.JDialog jd_administrator;
    private javax.swing.JDialog jd_agregar_atm;
    private javax.swing.JDialog jd_newatm;
    private javax.swing.JDialog jd_personnel;
    private javax.swing.JDialog jd_register;
    private javax.swing.JDialog jd_user_create;
    private javax.swing.JMenuItem jmi_addatm;
    private javax.swing.JTree jt_personal_mantenimiento;
    private javax.swing.JPasswordField pf_admin;
    private javax.swing.JPasswordField pf_create_user;
    private javax.swing.JTextField tf_admin;
    private javax.swing.JTextField tf_affilation;
    private javax.swing.JTextField tf_apellido_user;
    private javax.swing.JTextField tf_atm_ubicacion;
    private javax.swing.JTextField tf_birthdate;
    private javax.swing.JTextField tf_id_atm;
    private javax.swing.JTextField tf_id_user_create;
    private javax.swing.JTextField tf_nombre_create_iuser;
    private javax.swing.JTextField tf_productiondate_atm;
    private javax.swing.JTextField tf_segundoapellido_user;
    private javax.swing.JTextField tf_segundonombre;
    private javax.swing.JTextField tf_transacciones;
    // End of variables declaration//GEN-END:variables
    ArrayList<Administrador> admins = new ArrayList();
    Mantenimiento mant_seleccionado;
    atm atm_seleccionado;
    Cliente cliente_seleccionado;
    DefaultMutableTreeNode nodo_seleccionado;
}
