/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_erickcarrasco;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class Principal_frame extends javax.swing.JFrame {

    /**
     * Creates new form Principal_frame
     */
        
    administrarClientes ac = new administrarClientes("./clientes.txt");
    administrarMantenimiento am = new administrarMantenimiento("./mantenimiento.txt");
    public Principal_frame() {
        initComponents();
        admins.add(new Administrador("admin", "admin", "12345"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_register = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        crearuser = new javax.swing.JButton();
        crearatm = new javax.swing.JButton();
        jd_administrator = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_admin = new javax.swing.JTextField();
        pf_admin = new javax.swing.JPasswordField();
        jb_admin_ingresar = new javax.swing.JButton();
        jd_user_create = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        tf_id_user_create = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_nombre_create_iuser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_apellido_user = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_segundonombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_segundoapellido_user = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pf_create_user = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_transacciones = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_birthdate = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tf_affilation = new javax.swing.JTextField();
        cb_type_user = new javax.swing.JComboBox();
        jb_crearuser_xp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jb_ingresar = new javax.swing.JButton();
        jb_administrar = new javax.swing.JButton();
        cb_atms = new javax.swing.JComboBox();

        jLabel5.setText("Creation Admin");

        crearuser.setText("Usuario");
        crearuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearuserMouseClicked(evt);
            }
        });

        crearatm.setText("ATM");

        javax.swing.GroupLayout jd_registerLayout = new javax.swing.GroupLayout(jd_register.getContentPane());
        jd_register.getContentPane().setLayout(jd_registerLayout);
        jd_registerLayout.setHorizontalGroup(
            jd_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registerLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel5)
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(jd_registerLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(crearuser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(crearatm)
                .addGap(59, 59, 59))
        );
        jd_registerLayout.setVerticalGroup(
            jd_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(56, 56, 56)
                .addGroup(jd_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearuser)
                    .addComponent(crearatm))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jLabel2.setText("Credenciales");

        jLabel3.setText("User: ");

        jLabel4.setText("Password: ");

        jb_admin_ingresar.setText("Ingresar");
        jb_admin_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_admin_ingresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_administratorLayout = new javax.swing.GroupLayout(jd_administrator.getContentPane());
        jd_administrator.getContentPane().setLayout(jd_administratorLayout);
        jd_administratorLayout.setHorizontalGroup(
            jd_administratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_administratorLayout.createSequentialGroup()
                .addGroup(jd_administratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_administratorLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel2))
                    .addGroup(jd_administratorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_administratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(48, 48, 48)
                        .addGroup(jd_administratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_admin)
                            .addComponent(pf_admin, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_administratorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jb_admin_ingresar)
                .addGap(126, 126, 126))
        );
        jd_administratorLayout.setVerticalGroup(
            jd_administratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_administratorLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jd_administratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jd_administratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pf_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_admin_ingresar)
                .addGap(5, 5, 5))
        );

        jLabel6.setText("ID: ");

        jLabel7.setText("Nombre:");

        jLabel8.setText("Apellido:");

        jLabel9.setText("Segundo Nombre:");

        jLabel10.setText("Segundo Nombre:");

        jLabel11.setText("Password:");

        jLabel12.setText("Type:");

        jLabel13.setText("Transacciones: ");

        jLabel14.setText("Birth Date");

        jLabel15.setText("Affilation Year:");

        cb_type_user.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mantenimiento", "Cliente" }));

        jb_crearuser_xp.setText("Crear");
        jb_crearuser_xp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearuser_xpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_user_createLayout = new javax.swing.GroupLayout(jd_user_create.getContentPane());
        jd_user_create.getContentPane().setLayout(jd_user_createLayout);
        jd_user_createLayout.setHorizontalGroup(
            jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_user_createLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_id_user_create, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_user_createLayout.createSequentialGroup()
                        .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_user_createLayout.createSequentialGroup()
                                                        .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel6)
                                                            .addComponent(jLabel7)
                                                            .addComponent(jLabel8))
                                                        .addGap(73, 73, 73))
                                                    .addGroup(jd_user_createLayout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addGap(28, 28, 28)))
                                                .addGroup(jd_user_createLayout.createSequentialGroup()
                                                    .addComponent(jLabel10)
                                                    .addGap(28, 28, 28)))
                                            .addGroup(jd_user_createLayout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(61, 61, 61)))
                                        .addGroup(jd_user_createLayout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(36, 36, 36)))
                                    .addGroup(jd_user_createLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(67, 67, 67)))
                                .addGroup(jd_user_createLayout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(41, 41, 41)))
                            .addGroup(jd_user_createLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(87, 87, 87)))
                        .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_crearuser_xp)
                            .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tf_nombre_create_iuser, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_apellido_user, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_segundonombre, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_segundoapellido_user, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pf_create_user, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_transacciones, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_affilation, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cb_type_user, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jd_user_createLayout.setVerticalGroup(
            jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_user_createLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_id_user_create, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_nombre_create_iuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_segundonombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_apellido_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_segundoapellido_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pf_create_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_transacciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_affilation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_user_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(cb_type_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jb_crearuser_xp)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Eurostile Extended", 0, 18)); // NOI18N
        jLabel1.setText("ATM");

        jb_ingresar.setText("Ingresar ");

        jb_administrar.setText("Crear");
        jb_administrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_administrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_atms, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jb_administrar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jb_ingresar)
                .addGap(76, 76, 76)
                .addComponent(cb_atms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jb_administrar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_administrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_administrarMouseClicked
        // TODO add your handling code here:
        tf_admin.setText("");
        pf_admin.setText("");
        jd_administrator.setModal(true);
        jd_administrator.pack();
        jd_administrator.setLocationRelativeTo(this);
        jd_administrator.setVisible(true);
    }//GEN-LAST:event_jb_administrarMouseClicked

    private void jb_admin_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_admin_ingresarMouseClicked
        // TODO add your handling code here:
        String pass_verify=pf_admin.getText();
        String user= tf_admin.getText();
        String pass;
        String user_auth="";
        int c=0;
        int count=0;
        for (Object P : admins) {
            String userad = admins.get(c).getUser();
            if (user.equals(userad)) {
                user_auth= userad;
                count = c;
            }
            c++;
        }
        pass = admins.get(count).getPassword();
        if (pass_verify.equals(pass) && user.equals(user_auth)) {
            JOptionPane.showMessageDialog(jd_administrator, "Ingreso exitosamente "+ admins.get(count).getNombre());
            
            tf_admin.setText("");
            pf_admin.setText("");
            
            jd_register.setModal(true);
            jd_register.pack();
            jd_register.setLocationRelativeTo(this);
            jd_register.setVisible(true);
            jd_administrator.dispose();
        }
    }//GEN-LAST:event_jb_admin_ingresarMouseClicked

    private void crearuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearuserMouseClicked
        // TODO add your handling code here:
        jd_user_create.setModal(true);
        jd_user_create.pack();
        jd_user_create.setLocationRelativeTo(jd_register);
        jd_user_create.setVisible(true);
    }//GEN-LAST:event_crearuserMouseClicked

    private void jb_crearuser_xpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearuser_xpMouseClicked
        // TODO add your handling code here:
        String type = cb_type_user.getSelectedItem().toString();
        if (type.equals("Cliente")) {
            ac.cargarArchivo();
            String nombre, nombre2, apellido, apellido2, clave, birth, affilacion;
            String id;
            clave = pf_create_user.getText();
            nombre = tf_nombre_create_iuser.getText();
            nombre2 = tf_segundonombre.getText();
            apellido = tf_apellido_user.getText();
            apellido2 = tf_segundoapellido_user.getText();
            birth = tf_birthdate.getText();
            affilacion = tf_affilation.getText();
            id = tf_id_user_create.getText();

            int c = 0;
            boolean validador = true;
            for (Cliente p : ac.getListaClientes()) {
                String user = ac.getListaClientes().get(c).getId();
                if (user.equals(id)) {
                    JOptionPane.showMessageDialog(jd_user_create, "ID ya ocupada");
                    
                    validador = false;
                }
                c++;
            }
        
            if (validador) {
                ac.setCliente(new Cliente(id, nombre, nombre2, apellido, apellido2, clave, birth, affilacion));
                try {
                    ac.escribirArchivo();
                } catch (IOException ex) {
                    //Logger.getLogger(Login_menu.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(jd_user_create, "Se ingreso un nuevo usuario");
                jd_user_create.dispose();
                tf_id_user_create.setText("");
                tf_affilation.setText("");
                tf_birthdate.setText("");
                tf_apellido_user.setText("");
                tf_segundoapellido_user.setText("");
                tf_transacciones.setText("");
                tf_nombre_create_iuser.setText("");
                pf_create_user.setText("");
                //pf_password_nueva.setText("");
            }
            
            
        }
        if (type.equals("Mantenimiento")) {
            am.cargarArchivo();
            String nombre, nombre2, apellido, apellido2, clave, birth, affilacion;
            String id;
            clave = pf_create_user.getText();
            nombre = tf_nombre_create_iuser.getText();
            nombre2 = tf_segundonombre.getText();
            apellido = tf_apellido_user.getText();
            apellido2 = tf_segundoapellido_user.getText();
            birth = tf_birthdate.getText();
            affilacion = tf_affilation.getText();
            id = tf_id_user_create.getText();
            
            int c = 0;
            boolean validador = true;
            for (Mantenimiento m : am.getListaMantenimiento()) {
                String user = am.getListaMantenimiento().get(c).getId();
                if (user.equals(id)) {
                    JOptionPane.showMessageDialog(jd_user_create, "ID ya ocupada");
                    
                    validador = false;
                }
                c++;
            }
            
            if (validador) {
                am.setMantenimiento(new Mantenimiento(id, nombre, nombre2, apellido, apellido2, clave, birth, affilacion));
                try {
                    am.escribirArchivo();
                } catch (IOException ex) {
                    //Logger.getLogger(Login_menu.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(jd_user_create, "Se ingreso un nuevo usuario");
                jd_user_create.dispose();
                tf_id_user_create.setText("");
                tf_affilation.setText("");
                tf_birthdate.setText("");
                tf_apellido_user.setText("");
                tf_segundoapellido_user.setText("");
                tf_transacciones.setText("");
                tf_nombre_create_iuser.setText("");
                pf_create_user.setText("");
                //pf_password_nueva.setText("");
            }
            
        }
        
    }//GEN-LAST:event_jb_crearuser_xpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb_atms;
    private javax.swing.JComboBox cb_type_user;
    private javax.swing.JButton crearatm;
    private javax.swing.JButton crearuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jb_admin_ingresar;
    private javax.swing.JButton jb_administrar;
    private javax.swing.JButton jb_crearuser_xp;
    private javax.swing.JButton jb_ingresar;
    private javax.swing.JDialog jd_administrator;
    private javax.swing.JDialog jd_register;
    private javax.swing.JDialog jd_user_create;
    private javax.swing.JPasswordField pf_admin;
    private javax.swing.JPasswordField pf_create_user;
    private javax.swing.JTextField tf_admin;
    private javax.swing.JTextField tf_affilation;
    private javax.swing.JTextField tf_apellido_user;
    private javax.swing.JTextField tf_birthdate;
    private javax.swing.JTextField tf_id_user_create;
    private javax.swing.JTextField tf_nombre_create_iuser;
    private javax.swing.JTextField tf_segundoapellido_user;
    private javax.swing.JTextField tf_segundonombre;
    private javax.swing.JTextField tf_transacciones;
    // End of variables declaration//GEN-END:variables
    ArrayList<Administrador> admins = new ArrayList();
}
